project_id: '705759'
preserve_hierarchy: true
files:
  # JSON translation files
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  # Wiki Markdown files
  - source: /wiki/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  # Blog Markdown files
  - source: /blog/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%
  - source: /openapi/**/*
    translation: /i18n/%two_letters_code%/openapi/**/%original_file_name%
  - source: /src/data/providers.ts
    translation: /i18n/%two_letters_code%/src/data/providers.ts